---
- name: Test ansible proxmox stuff 
  hosts: proxmox.intern.k4cg.org

  tasks:
  - name: Get state of a specific vm
    community.general.proxmox_kvm:
      api_user: "{{ proxmox_user }}"
      api_password: "{{ proxmox_password }}"
      api_host: "{{ ip_address }}"
      vmid: 101
      state: current
    delegate_to: localhost
    register: proxmox_response

  - name: debug proxmox server response
    ansible.builtin.debug:
      var: proxmox_response

  # - name: Get state of a specific vm
  #   community.general.proxmox_kvm:
  #     api_user: "{{ proxmox_host2.user }}"
  #     api_password: "{{ proxmox_host2.password }}"
  #     api_host: "{{ proxmox_host2.ip_address }}"
  #     vmid: 9900
  #     state: current
  #   register: proxmox_response
