name: Development workflow

on:
  push:
    branches-ignore: [ main ]
    paths: 
      - ./Dockerfile
  pull_request:
    branches: [ main ]
    paths: 
      - ./Dockerfile

jobs:
  lint: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run hadolint action
      uses: hadolint/hadolint-action@v1.6.0
      with:
        # A space separated string of rules to ignore, optional
        ignore: DL3008

  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag k4cg-automation:${{ github.sha }}
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.2.2
      with:
        image-ref: 'k4cg-automation:${{ github.sha }}'
        severity: 'CRITICAL,HIGH'
        format: 'table'
        exit-code: 1
